# Generated by Django 4.2.13 on 2024-07-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubDisplay', '0003_project_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
