# Generated by Django 4.2.13 on 2024-07-15 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('githubDisplay', '0009_userprofile_profile_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.JSONField()),
                ('summary', models.TextField()),
                ('education', models.JSONField()),
                ('skills', models.JSONField()),
                ('experience', models.JSONField()),
                ('projects', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
