# Generated by Django 4.2.13 on 2024-07-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubDisplay', '0010_resumesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesummary',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='uploads/pdfs/'),
            preserve_default=False,
        ),
    ]
