# Generated by Django 4.2.13 on 2024-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubDisplay', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
