# Generated by Django 4.2.13 on 2024-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubDisplay', '0004_project_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_projects',
            field=models.ManyToManyField(blank=True, to='githubDisplay.project'),
        ),
    ]
