# Generated by Django 4.2.13 on 2024-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubDisplay', '0012_alter_resumesummary_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesummary',
            name='images',
            field=models.ImageField(null=True, upload_to='uploads/images/resumes/'),
        ),
    ]
